receivers:
  fluentforward:
    endpoint: 0.0.0.0:24224

processors:
  batch: {}

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: [batch]
      exporters: [debug]
